on:
  repository_dispatch:
    types: [package]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: default
    name: package
    container: archlinux:base-devel
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          pacman-key --init
          pacman -Syu --noconfirm \
            --ignore linux \
            --ignore linux-firmware \
            --needed base-devel \
            --needed go \
            --needed aarch64-linux-gnu-binutils \
            --needed openssh

          # Ensure wheel group exists (seriously??)
          groupadd -f -r wheel

          # Create an unprivileged user
          useradd -m -G wheel -s /bin/bash pkguser

          # Grant group wheel sudo rights without password.
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel

          # Run pkgbuild script as unprivileged user
          og=$(stat -c '%u:%g' .)
          chown -R pkguser: .

          cd ${{ github.event.client_payload.REPO }}
          sudo -u pkguser makepkg --config ../${{ github.event.client_payload.ARCH }}.conf -fc

      # - name: ZeroTier
      #   uses: zerotier/github-action@v1.0.1
      #   with:
      #     network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
      #     auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      # - name: build
      #   uses: ./.github/actions/build
      #   id: build
      #   with:
      #     arch: ${{ github.event.client_payload.ARCH }}
      #     repo: ${{ github.event.client_payload.REPO }}
      #     upload_key: ${{ secrets.UPLOAD_KEY }}
      #     upload_host: ${{ secrets.UPLOAD_HOST }}
      - shell: bash
        run: |
          ls -l /
          ls -l /tmp
          ls -l /tmp/repo
