on:
  repository_dispatch:
    types: [package]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: default
    name: package
    container: archlinux:base-devel
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          pacman-key --init
          pacman -Syu --noconfirm \
            --ignore linux \
            --ignore linux-firmware \
            --needed base-devel \
            --needed go \
            --needed aarch64-linux-gnu-binutils \
            --needed openssh

          # Ensure wheel group exists (seriously??)
          groupadd -f -r wheel

          # Create an unprivileged user
          useradd -m -G wheel -s /bin/bash pkguser

          # Grant group wheel sudo rights without password.
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel

          # Run pkgbuild script as unprivileged user
          og=$(stat -c '%u:%g' .)
          chown -R pkguser: .

          cd ${{ github.event.client_payload.REPO }}
          sudo -u pkguser makepkg --config ../${{ github.event.client_payload.ARCH }}.conf -fc

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.REPO }}
          path: /tmp/repo/*.zst

  upload:
    runs-on: ubuntu-latest
    environment: default
    name: upload
    needs: [dispatch]
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ github.event.client_payload.REPO }}

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USER }}
          key: ${{ secrets.UPLOAD_KEY }}
          port: 22
          source: "${{ github.event.client_payload.REPO }}*.zst"
          target: /tmp

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USER }}
          key: ${{ secrets.UPLOAD_KEY }}
          port: 22
          script: |
            ls -l /tmp
            ARTIFACT=$(ls /tmp/*.zst)
            sudo cp ${ARTIFACT} /mnt/nfssever/apps/repo/${{ github.event.client_payload.ARCH }}/
            # rm /tmp/*.zst
            sudo /mnt/nfsserver/apps/repo/${{ github.event.client_payload.ARCH }}/create_repo.sh
