on:
  repository_dispatch:
    types: [package]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: package
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: ./.github/actions/build
        id: build
        with:
          arch: ${{ github.event.client_payload.ARCH }}
          repo: ${{ github.event.client_payload.REPO }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.REPO }}
          path: /tmp/repo/**/*.zst
