on:
  repository_dispatch:
    types: [package]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: default
    name: package ${{ github.event.client_payload.REPO }}
    container: archlinux:base-devel
    outputs:
      artifact: ${{ steps.artifact.outputs.ARTIFACT }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          pacman-key --init
          pacman -Syu --noconfirm \
            --ignore linux \
            --ignore linux-firmware \
            --needed base-devel \
            --needed go \
            --needed aarch64-linux-gnu-binutils \
            --needed jq \
            --needed libx11 \
            --needed libxft \
            --needed nodejs

          # Ensure wheel group exists (seriously??)
          groupadd -f -r wheel

          # Create an unprivileged user
          useradd -m -G wheel -s /bin/bash pkguser

          # Grant group wheel sudo rights without password.
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel

          # Run pkgbuild script as unprivileged user
          og=$(stat -c '%u:%g' .)
          chown -R pkguser: .

          cd ${{ github.event.client_payload.REPO }}
          sudo -u pkguser makepkg --config ../${{ github.event.client_payload.ARCH }}.conf -fc

      - name: Get artifact
        id: artifact_path
        run: echo "ARTIFACT_PATH=$(ls /tmp/repo/*.zst)" >> "${GITHUB_OUTPUT}"

      - name: Get artifact path
        id: artifact
        run: echo "ARTIFACT=$(basename ${{ steps.artifact_path.outputs.ARTIFACT_PATH }})" >> "${GITHUB_OUTPUT}"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.REPO }}
          path: ${{ steps.artifact_path.outputs.ARTIFACT_PATH }}

  upload:
    runs-on: ubuntu-latest
    environment: default
    name: upload ${{ github.event.client_payload.REPO }}
    needs: dispatch
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ github.event.client_payload.REPO }}

      - name: 'Echo download path'
        run: echo ${{ steps.download.outputs.download-path }}

      - uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USER }}
          key: ${{ secrets.UPLOAD_KEY }}
          port: ${{ secrets.UPLOAD_PORT }}
          source: "${{ github.event.client_payload.REPO }}*.zst"
          target: /tmp

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USER }}
          key: ${{ secrets.UPLOAD_KEY }}
          port: ${{ secrets.UPLOAD_PORT }}
          script: |
            REPO_DIR=/mnt/nfsserver/apps/repo/${{ github.event.client_payload.ARCH }}
            ARTIFACT=/tmp/${{ needs.dispatch.outputs.artifact }}
            sudo cp ${ARTIFACT} ${REPO_DIR}
            rm ${ARTIFACT}

            n=0
            until [ "$n" -ge 5 ]; do
              if [[ ! -f ${REPO_DIR}/personal.db.tar.gz.lck ]]; then
                sudo ${REPO_DIR}/create_repo.sh
                break
              fi
              n=$((n+1))
              sleep 15
            done

      - name: 'Notify'
        run: curl -d "Build successful" ntfy.sh/${{ secrets.NTFY_TOPIC }}
