on:
  repository_dispatch:
    types: [package]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: default
    name: package
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: build
        uses: ./.github/actions/build
        id: build
        with:
          arch: ${{ github.event.client_payload.ARCH }}
          repo: ${{ github.event.client_payload.REPO }}
