---
name: pacman

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Create artifacts
    steps:
      - uses: actions/checkout@v1

      - name: Create aarch64 servus
        id: servus-aarch64
        uses: DictumMortuum/arch-pkgbuild-builder@v1.20
        with:
          target: 'pkgbuild'
          pkgname: 'servus'
          makepkg: 'aarch64.conf'

      - name: Create x86_64 i3-utils
        id: i3-utils-x86_64
        uses: DictumMortuum/arch-pkgbuild-builder@v1.20
        with:
          target: 'pkgbuild'
          pkgname: 'i3-utils'
          makepkg: 'x86_64.conf'

      - name: Create aarch64 servus-admin
        id: servus-admin-aarch64
        uses: DictumMortuum/arch-pkgbuild-builder@v1.20
        with:
          target: 'pkgbuild'
          pkgname: 'servus-admin'
          makepkg: 'aarch64.conf'

      - run: |
          cd /tmp/repo
          repo-add -R personal.db.tar.gz *aarch64*.pkg.tar.zst >> build.log
          repo-add -R personal-x86_64.tar.gz *x86_64*.pkg.tar.zst >> build.log

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/repo/*.tar.zst
          file_glob: true
          tag: ${{ github.ref }}

      - name: Upload repositories
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./servus/*.db.tar.gz
          file_glob: true
          tag: ${{ github.ref }}
