---
name: servus

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: DictumMortuum/arch-pkgbuild-builder@v1.19
        with:
          target: 'pkgbuild'
          pkgname: 'servus'
          makepkg: 'aarch64_github.conf'

      # - name: Upload artifacts
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./servus/*.tar.zst
      #     file_glob: true
      #     tag: ${{ github.ref }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./servus/*.tar.zst
